name: publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: macos-latest
          CHANNEL: osx
        - os: ubuntu-latest
          CHANNEL: linux
        - os: windows-latest
          CHANNEL: windows
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Zip Windows
      if: matrix.os == 'windows-latest'
      run: zip game.zip target/release/game.exe \
        resources/tilemap.png \
        resources/spritesheet.png \
        resources/tilemap.tmx
    - name: Zip MacOS/Linux
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      run: zip game.zip target/release/game \
        resources/tilemap.png \
        resources/spritesheet.png \
        resources/tilemap.tmx
    - name: Butler Push
      uses: josephbmanley/butler-publish-itchio-action@v1.0.1
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: ${{matrix.TARGET}}
        ITCH_GAME: ascension-2
        ITCH_USER: outkine
        PACKAGE: game.zip
