name: publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libasound2-dev libudev-dev pkg-config
    - name: Build
      run: cargo build --release

    - name: Create Dist Folder Windows
      if: matrix.os == 'windows-latest'
      run: |
        mkdir dist/resources
        cp -Path target/release/game.exe -Destination dist
        cp -Path resources/tilesheet.png,resources/spritesheet.png,resources/tilemap.tmx,resources/Pixellari.ttf -Destination dist/resources

    - name: Create Dist Folder MacOS/Linux
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p dist/resources
        cp target/release/game dist
        cp resources/tilesheet.png resources/spritesheet.png resources/tilemap.tmx resources/Pixellari.ttf dist/resources

    - uses: actions/upload-artifact@v2-preview
      with:
        name: ascension-2-${{ matrix.os }}
        path: dist
